version: '3.8'
services:
  eureka-server:
    build:
      context: .
      dockerfile: examples/eureka-server/Dockerfile
    ports:
      - "8761:8761"

  kafureka-sidecar:
    build:
      context: .
      dockerfile: kafureka-broker-sidecar/Dockerfile
    depends_on:
      - eureka-server
      - kafka
    ports:
      - "8081:8081"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  producer:
    build:
      context: .
      dockerfile: examples/producer-example/Dockerfile
    depends_on:
      - kafka
      - kafureka-sidecar
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  consumer:
    build:
      context: .
      dockerfile: examples/consumer-example/Dockerfile
    depends_on:
      - kafka
      - kafureka-sidecar
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/