server:
  port: 8080

spring:
  application:
    name: kafka-broker
  cloud:
    inetutils:
      preferred-networks:
        - 172.

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    non-secure-port: ${KAFKA_PORT:9092}
